language: ruby
rvm: "2.1.1"

# to enable javascript testing with X server and firefox
before_install:
  - gem install bundler

before_script:
  - bundle exec rake db:create:all
  - bundle exec rake db:migrate

script:
  #- bundle exec rspec --format progress
  - bundle exec rake jasmine:ci
  #- bundle exec cucumber --profile ci
  - bundle exec rake test_with_coveralls

# downgrade git version to avoid deployment bug (keep till its fixed)
before_install:
  - sudo rm /etc/apt/sources.list.d/git-ppa-source.list
  - sudo apt-get remove git && sudo apt-get remove git-man && sudo apt-get install git-man && sudo apt-get install git

deploy:
  provider: heroku
  api_key:
    secure: qjGSUm5TSMjgarhzvBnZhNVyMcLCXpszb68D+aj9rKtNwHggz2dmCyqATr3Ynl38I193/QEaOUEarHguI7ABSW6SCmdAIoAEP/h7bbyOgLAYV9+ct/qhk8N4PdjnKUYUYZ9lsd5UcErMMgD03USQg3CeG1X1LwSX18jcScBHkss=
  strategy: git
  app:
      develop: websiteone-develop
      staging: websiteone-staging
      master: websiteone-production
  run: "rake db:migrate"
