features:
  custom_errors:
    enabled: false
  slack:
    notifications:
      enabled: false
    invites:
      enabled: false
  welcome_email:
    enabled: false

hangouts:
  app_id: '331105831845'
